name: cuatro_ruedas
description: A new Flutter application.


version: 1.0.0+1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
 # flutter_facebook_login: ^1.1.1
  firebase_auth: ^0.5.18
  cloud_firestore: ^0.8.2+3
  firebase_storage: ^1.0.4
  google_sign_in: ^3.0.4
  fluttertoast: ^2.1.1
  shared_preferences: ^0.4.3
  cached_network_image: ^0.5.1
  image_picker: ^0.4.10
  advanced_share: ^0.1.0
  intl: ^0.15.7
  flutter_ibm_watson: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true
  assets:
  - assets/logo.png
  - assets/google.png
  - assets/tp.jpeg
  - assets/soat.jpeg
  - assets/cc.jpeg
  - assets/twitter.png
  - assets/user_no_found.png

